-- KAYAN CITY SPOT marketing center
-- Additive migration: existing directory records and analytics remain valid.

create table if not exists public.marketing_channels (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 80),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9_-]{2,39}$'),
  whatsapp_url text not null check (
    whatsapp_url ~ '^https://(chat\.whatsapp\.com|whatsapp\.com/channel)/[A-Za-z0-9_-]+'
  ),
  notes text not null default '' check (char_length(notes) <= 500),
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_campaigns (
  id uuid primary key default gen_random_uuid(),
  channel_id uuid not null references public.marketing_channels(id) on delete cascade,
  entity_type text not null check (entity_type in ('site', 'place', 'driver', 'feature')),
  entity_id uuid,
  template_key text not null check (
    template_key in (
      'new_place',
      'new_driver',
      'weekly_roundup',
      'merchant_invite',
      'driver_invite',
      'missing_service',
      'data_correction',
      'local_ambassadors',
      'general_site'
    )
  ),
  campaign_code text not null unique default
    substring(replace(gen_random_uuid()::text, '-', '') from 1 for 16),
  status text not null default 'draft' check (status in ('draft', 'published')),
  payload jsonb not null default '{}'::jsonb check (
    jsonb_typeof(payload) = 'object'
    and pg_column_size(payload) <= 4096
  ),
  created_by uuid references auth.users(id) on delete set null,
  last_published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (entity_type in ('place', 'driver') and entity_id is not null)
    or (entity_type in ('site', 'feature') and entity_id is null)
  )
);

create unique index if not exists marketing_campaign_entity_channel_idx
  on public.marketing_campaigns (
    channel_id,
    entity_type,
    coalesce(entity_id, '00000000-0000-0000-0000-000000000000'::uuid),
    template_key
  );
create index if not exists marketing_campaigns_channel_status_idx
  on public.marketing_campaigns (channel_id, status, updated_at desc);
create index if not exists marketing_campaigns_code_idx
  on public.marketing_campaigns (campaign_code);

create table if not exists public.marketing_publications (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.marketing_campaigns(id) on delete cascade,
  published_by uuid references auth.users(id) on delete set null,
  published_at timestamptz not null default now()
);

create index if not exists marketing_publications_campaign_date_idx
  on public.marketing_publications (campaign_id, published_at desc);

alter table public.marketing_channels enable row level security;
alter table public.marketing_campaigns enable row level security;
alter table public.marketing_publications enable row level security;

revoke all on public.marketing_channels from public, anon, authenticated;
revoke all on public.marketing_campaigns from public, anon, authenticated;
revoke all on public.marketing_publications from public, anon, authenticated;
grant select, insert, update, delete on public.marketing_channels to service_role;
grant select, insert, update, delete on public.marketing_campaigns to service_role;
grant select, insert on public.marketing_publications to service_role;
grant usage, select on sequence public.marketing_publications_id_seq to service_role;

insert into public.marketing_channels (
  name,
  slug,
  whatsapp_url,
  notes,
  is_active
)
values (
  'KAYAN CITY SPOT',
  'kayan-main',
  'https://chat.whatsapp.com/JTuPs9xv0CZAZhpzxttU3R?s=cl&p=i&ilr=0',
  'الجروب الرسمي للموقع',
  true
)
on conflict (slug) do update
set whatsapp_url = excluded.whatsapp_url,
    updated_at = now();

alter table public.analytics_daily_events
  add column if not exists campaign_key text not null default ''
  check (campaign_key ~ '^[a-zA-Z0-9_-]{0,64}$');

alter table public.analytics_daily_events
  drop constraint if exists analytics_daily_events_event_name_check;
alter table public.analytics_daily_events
  add constraint analytics_daily_events_event_name_check check (
    event_name in (
      'page_view',
      'place_open',
      'driver_open',
      'phone_click',
      'whatsapp_click',
      'group_click',
      'telegram_click',
      'map_click',
      'share_click',
      'marketing_share_click',
      'card_download',
      'guide_open',
      'favorite_click',
      'upvote_click',
      'search_use',
      'category_select',
      'join_open',
      'feedback_open',
      'add_listing_open',
      'driver_signup_open',
      'support_click'
    )
  );

alter table public.analytics_daily_events
  drop constraint if exists analytics_daily_events_target_type_check;
alter table public.analytics_daily_events
  add constraint analytics_daily_events_target_type_check check (
    target_type in ('site', 'place', 'driver', 'category', 'feature')
  );

alter table public.analytics_daily_events
  drop constraint if exists analytics_daily_events_pkey;
alter table public.analytics_daily_events
  add primary key (
    event_date,
    event_name,
    target_type,
    target_key,
    route,
    campaign_key
  );

create or replace function public.record_site_analytics_v2(
  p_visitor_hash text,
  p_event_name text,
  p_target_type text,
  p_target_key text,
  p_route text,
  p_campaign_key text default '',
  p_limit integer default 120
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_attempts integer;
  v_campaign_key text;
begin
  if coalesce(auth.jwt() ->> 'role', '') <> 'service_role' then
    raise exception 'service_role_required';
  end if;

  v_campaign_key := coalesce(p_campaign_key, '');
  if p_visitor_hash !~ '^[a-f0-9]{64}$'
     or p_event_name not in (
       'page_view', 'place_open', 'driver_open', 'phone_click',
       'whatsapp_click', 'group_click', 'telegram_click', 'map_click',
       'share_click', 'marketing_share_click', 'card_download', 'guide_open',
       'favorite_click', 'upvote_click', 'search_use', 'category_select',
       'join_open', 'feedback_open', 'add_listing_open',
       'driver_signup_open', 'support_click'
     )
     or p_target_type not in ('site', 'place', 'driver', 'category', 'feature')
     or char_length(p_target_key) > 64
     or v_campaign_key !~ '^[a-zA-Z0-9_-]{0,64}$'
     or p_route !~ '^/[a-zA-Z0-9/_-]*$'
     or char_length(p_route) > 120
     or p_limit not between 1 and 500 then
    raise exception 'invalid_analytics_input';
  end if;

  insert into public.analytics_rate_limits (
    visitor_hash, window_started_at, attempts, updated_at
  )
  values (p_visitor_hash, now(), 1, now())
  on conflict (visitor_hash) do update
  set window_started_at = case
        when analytics_rate_limits.window_started_at <= now() - interval '1 hour'
          then now()
        else analytics_rate_limits.window_started_at
      end,
      attempts = case
        when analytics_rate_limits.window_started_at <= now() - interval '1 hour'
          then 1
        else analytics_rate_limits.attempts + 1
      end,
      updated_at = now()
  returning attempts into v_attempts;
  if v_attempts > p_limit then return false; end if;

  insert into public.analytics_daily_visitors (event_date, visitor_hash, last_seen_at)
  values (current_date, p_visitor_hash, now())
  on conflict (event_date, visitor_hash) do update
  set last_seen_at = now();

  insert into public.analytics_daily_events (
    event_date,
    event_name,
    target_type,
    target_key,
    route,
    campaign_key,
    events,
    updated_at
  )
  values (
    current_date,
    p_event_name,
    p_target_type,
    p_target_key,
    p_route,
    v_campaign_key,
    1,
    now()
  )
  on conflict (
    event_date,
    event_name,
    target_type,
    target_key,
    route,
    campaign_key
  )
  do update set
    events = analytics_daily_events.events + 1,
    updated_at = now();

  if pg_catalog.random() < 0.01 then
    delete from public.analytics_rate_limits
    where updated_at < now() - interval '2 hours';
    delete from public.analytics_daily_visitors
    where event_date < current_date - 30;
    delete from public.analytics_daily_events
    where event_date < current_date - 180;
  end if;
  return true;
end;
$$;

revoke all on function public.record_site_analytics_v2(
  text, text, text, text, text, text, integer
) from public, anon, authenticated;
grant execute on function public.record_site_analytics_v2(
  text, text, text, text, text, text, integer
) to service_role;

-- Keep the previous server release working during a rolling deployment.
create or replace function public.record_site_analytics(
  p_visitor_hash text,
  p_event_name text,
  p_target_type text,
  p_target_key text,
  p_route text,
  p_limit integer default 120
)
returns boolean
language sql
security invoker
set search_path = ''
as $$
  select public.record_site_analytics_v2(
    p_visitor_hash,
    p_event_name,
    p_target_type,
    p_target_key,
    p_route,
    '',
    p_limit
  );
$$;

revoke all on function public.record_site_analytics(
  text, text, text, text, text, integer
) from public, anon, authenticated;
grant execute on function public.record_site_analytics(
  text, text, text, text, text, integer
) to service_role;
